.TH "QDACCO" "1" 
.SH "NAME" 
qdacco \(em dacco english-catalan dictionary frontend 
.SH "SYNOPSIS" 
.PP 
\fBqdacco\fR [\fB-d \fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBqdacco\fR command. 
.PP 
This manual page was written for the \fBDebian\fP distribution 
because the original program does not have a manual page. 
.PP 
\fBqdacco\fR is a program that is able to search 
in the Dacco database to translate from english to catalan o viceversa. 
 
.SH "OPTIONS" 
.PP 
This program follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. 
.IP "\fB-d\fP         " 10 
Enable debug mode. 
.SH "AUTHOR" 
.PP 
This manual page was written by Miguel Gea Milvaques xerakko@debian.org for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 3 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Tue 05 Apr 2011, 20:26 
