.\" 
.TH "TEXTDACCO" "1" "February 2008" "Miguel Gea Milvaques" "User Commands"
.SH "NAME"
textdacco \- text frontend for dacco dictionary
.SH "DESCRIPTION"
textqdacco is a text version offline Dacco Catalan <\-> English dictionary frontend.
 Dacco is a free Catalan\-English dictionary and qdacco is a frontend to
 use this dictionary.
.SH "USAGE"
\fB\-\-cateng\fR or \fB\-\-engcat\fR Translate from/to Catalan to/from English
.br 
\fB\-\-path\fR PATH_TO_DICT Alternate path for dacco dictionary
.br 
\fB\-\-debug\fR optional 
.br 
\fB\-\-silent\fR Do not show the GPL disclaimer
.br 
\fB\-\-help\fR Show this help page
.br 
.SH "SEE ALSO"
.B qdacco (1) 
.SH "AUTHOR"
This manual page was written by Miguel Gea Milvaques xerakko@debian.org
for the Debian system (but may  be  used  by  others).   Permission  is
granted to copy, distribute and/or modify this document under the terms
of the GNU General Public License, Version 3  any  later  version  
published by the Free Software Foundation.

On  Debian systems, the complete text of the GNU General Public License
can be found in /usr/share/common\-licenses/GPL.
