######################################################################
# Automatically generated by qmake (2.01a) ds. nov. 17 17:40:45 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../core/auxiliar.h
SOURCES += textdacco.cpp ../core/auxiliar.cpp
